[common-etcd]
host = "127.0.0.1:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
userName = ""
password = ""
connectionTimeout = 5

[common-redis]
redisAddress = "127.0.0.1:6379"
redisPassword = ""
db = 0

[common-mysql]
host = "127.0.0.1:3306"
username = "root"
password = "123456"
maxConnections = 100
maxIdleConnections = 20
timeout = "10s"
dbname = "gochat"